"""cards table

Revision ID: 15e32141c1e9
Revises: 6cded54ac14b
Create Date: 2021-10-06 10:35:19.273927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e32141c1e9'
down_revision = '6cded54ac14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    op.create_index(op.f('ix_boxes_date_created'), 'boxes', ['date_created'], unique=False)
    op.drop_index('ix_box_date_created', table_name='box')
    op.drop_table('box')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box',
    sa.Column('box_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('box_id')
    )
    op.create_index('ix_box_date_created', 'box', ['date_created'], unique=False)
    op.drop_index(op.f('ix_boxes_date_created'), table_name='boxes')
    op.drop_table('boxes')
    # ### end Alembic commands ###
